"""new weight and discount price

Revision ID: 0a243e84cc84
Revises: 52c968e98d85
Create Date: 2025-11-03 19:46:51.891760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a243e84cc84'
down_revision = '52c968e98d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_price', sa.Float(), nullable=True))
        batch_op.alter_column('weight',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_constraint('products_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('products_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('products_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['uploader_id'], ['id'])
        batch_op.create_foreign_key(None, 'pet_types', ['pet_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_ibfk_3', 'pet_types', ['pet_type_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('products_ibfk_2', 'users', ['uploader_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('products_ibfk_1', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('weight',
               existing_type=sa.String(length=50),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('discount_price')

    # ### end Alembic commands ###
