"""Add cascade delete with named constraints

Revision ID: fc1d8406cada
Revises: 86f02401d94d
Create Date: 2025-09-25 15:30:29.463378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1d8406cada'
down_revision = '86f02401d94d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'pet_types', ['pet_type_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_ibfk_1', 'pet_types', ['pet_type_id'], ['id'])

    # ### end Alembic commands ###
